### ISSUE TITLE
LivePolishTV - Offline

### ISSUE THREAD

**Issue by BrownEmmett** [ramicspa/kodi#243]
Cześć, włączyłem dzisiaj wtyczkę LivePolishTV i mam dwie pozycje. Informacje o tym JanuszuBiznesu co kręcił lody na twoich wtyczkach oraz na czerwono Offline.
Mam coś skopane czy wtyczką póki co nie będzie działać?
Dzięki za świetną robotę! :)

**Comment by tomasiek** [comment]
Tymczasowo offline, zdarza się czasem w tym dodatku. Spróbuj za jakiś czas.

24.04.2017 12:58 AM "BrownEmmett" <notifications@github.com> napisał(a):

**Comment by BrownEmmett** [comment]
@tomasiek dzięki, dziś faktycznie działa. :)

**Comment by ramicspa** [comment]
ta wtyczka tak ma ze od czasu do czasu musi troche odpoczac.
przy nastepnej aktualizacji postaram sie usunac ta niedogodnosc.

**Comment by BrownEmmett** [comment]
@tomasiek @ramicspa dzięki, dziś faktycznie działa. :)

**Comment by koladka** [comment]
Ramic jaki kod do wtyczki? O co chodzi? Po aktualizacji dzis czyli 29.04.17.

**Comment by tomasiek** [comment]
I kolejny który nie czyta komunikatu z zamiast wejść na stronę, to wchodzi
na stronę, loguje się, pisze posta.... Wejdź na główną stronę repo, i
przewiń ja troszkę, zobaczysz nowy kod.

29.04.2017 5:03 PM "koladka" <notifications@github.com> napisał(a):

**Comment by koladka** [comment]
Ja mam wtyczke tylko z tv gdyz reszta mi niepotrzebna i dlatego pisze na info tego niema poprostu

**Comment by tomasiek** [comment]
Na stronie głównej repozytorium jest kod. W pytaniu o kod maszninformacje
że masz wejść na stronę repozytorium, nie że masz zakładać wątek  i czy
pytac. Kod jest cały czas na stronie. Po prostu nie chce ci się nawet
przewinąć strony. Nie podajemy go we wpisach, bo on się zmienia. Może być
już inny niż 15 minut temu. Dlatego ponownie odsyłam cię do strony głównej
i skorzystania z kółka myszki.
https://github.com/ramicspa/kodi


29.04.2017 5:12 PM "koladka" <notifications@github.com> napisał(a):

Ja mam wtyczke tylko z tv gdyz reszta mi niepotrzebna i dlatego pisze na
info tego niema poprostu

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/243#issuecomment-298174854>, or mute
the thread
