### ISSUE TITLE
TVP.pl wersja 2.0.1 nie dziala

### ISSUE THREAD

**Issue by adams2** [ramicspa/kodi#341]
nie wiem co sie dzieje ale TVP.pl wersja 2.0.1 nie dziala. Poprzednia 2.0.0 byla OK. Jak moge wyinstalowac 2.0.1 i zainstalowac powtornie 2.0.0?

**Comment by tomasiek** [comment]
Zamiast się cofać, lepiej podać log kodi albo opisać co dokładnie nie
działa. Ramicspa poprawi wtedy na pewno błąd i w kolejnej wersji będzie
działać.

24.06.2017 8:10 AM "adams2" <notifications@github.com> napisał(a):

nie wiem co sie dzieje ale TVP.pl wersja 2.0.1 nie dziala. Poprzednia 2.0.0
byla OK. Jak moge wyinstalowac 2.0.1 i zainstalowac powtornie 2.0.0?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/341>, or mute the thread

**Comment by adams2** [comment]
Spróbujmy to co proponujesz, zobaczymy czy zadziała. 
Otóż tak jak zwykle uruchamiam TurboVPN z połączeniem do Anglii i uruchamiam TVP.pl  i próbuję uruchomić archiwalne Wiadomości. System przez chwilę coś robi a potem jest komunikat: "One or more items failed to play. Check the log for more information about this message". Przeglądałem log ale raczej jeszcze nie rozumiem jego zawartości. Załączam go poniżej.

[kodi.txt](https://github.com/ramicspa/kodi/files/1100121/kodi.txt)

**Comment by ramicspa** [comment]
jak uzywasz vpn to lacz sie przez PL a nie UK bedzie duzo lepiej dzialac - odnosci to do wiekszosci polskich serwisow

**Comment by adams2** [comment]
niestety nie mam dostępu to polskiego serwera. Muszę łączyc się przez UK. Poza tym wszystko działało bardzo dobrze do ostatniej aktualizacji. Coś się zmieniło gdy wypuściliście 2.0.1. 
Jeżeli nie jesteście w stanie poprawić błędu, proszę powiedz mi w jaki sposób przywróciwszy poprzednią wersję 2.0.0. Z tej wersji byłem bardzo zadowolony.

**Comment by ramicspa** [comment]
wrzucilem nowa wersje wtyczki ... powinno lepiej dzialac przez zagraniczne vpn

**Comment by adams2** [comment]
nie wiem co poprawiłeś ale dziękuje. Wszystko działa.
