### ISSUE TITLE
nowa str z tv

### ISSUE THREAD

**Issue by plumers** [ramicspa/kodi#374]
http://openkatalog.ml

http://odpaltv.pl 

proszę dodać do livetv :) pozdro

**Comment by Katapulta** [comment]
To nie koncert życzeń haha :) Swoją drogą - strony ubogie i to bardzo. Jak w zawartość tak w źródła. Moim zdaniem bezsensu na tracenie czasu na nie i "zapychanie" wtyczek .

**Comment by tomasiek** [comment]
Ten pierwszy link to jakaś porażka. Nie znalazłem tam absolutnie nic z
testowej listy. Porażka jakich mało.
Drugi to tv, wie nie moja bajka

16.07.2017 7:44 PM "Katapulta" <notifications@github.com> napisał(a):

To nie koncert życzeń haha :) Swoją drogą - strony ubogie i to bardzo. Jak
w zawartość tak w źródła. Moim zdaniem bezsensu na tracenie czasu na nie i
"zapychanie" wtyczek .

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/374#issuecomment-315624760>, or mute
the thread

**Comment by plumers** [comment]
a kto was pyta o zdanie - zrobić własne repo i sapać ---- neoKids :(

**Comment by tomasiek** [comment]
No podejrzewam że ramicspa zarówno zdanie Katapulty jak i moje bierze pod uwagę, co nie raz, nie dwa już pokazał. Strona z filmami jest słabiutka, nie ma na niej filmów z topboxów, jest kilka nowości, ale ilość źródeł nie powala. Także szkoda na nią czasu, a tym bardziej pracy. A co do zrobienia własnego repo... Zrób własne i nie sapaj 😀

**Comment by tomasiek** [comment]
Ps..
 Interstellar w 480px z jednego źródła... Kurcze masochizm jakiś...

**Comment by clowni** [comment]
@ramicspa Pisalem wczesniej na temat wtyczki, ze Wizja TV uzywa portu 81 w adresie IP dla uzytkownikow premium, natomiast uzytkownicy standard sa na 80 i stad limit uzywania Wizja TV tylko 3h, gdzie czesto jest to mniej. Prosilem o ta poprawke.

Natomiast inna sprawa tworze listy TV i ciagle mi nic nie chodzi na Kodi Jarvis 16.1, mam crona i ustawienia tak jak opisane i ciagle nie chca mi sie ladowac streamy. Co mozna poprawic ?
