### ISSUE TITLE
player

### ISSUE THREAD

**Issue by lampardzino** [ramicspa/kodi#449]
Witam czy jest szansa zeby mozna bylo sie zalogowac na konto premium na player zeby np ogladać przedpremierowe odcinki nawspólnej bo jak sie zaloguje to mam dostep do 4 nowych odcinkow ktorych nie ma w boxie

**Comment by ramicspa** [comment]
jaki player?

**Comment by tomasiek** [comment]
Podejrzewam że chodzi o player.pl bo to chyba tam na wspólnej leci i jako
tako są dostępne odcinki premierowe. Problem w tym, że tej wtyczki nie ma w
repozytorium...
Albo komuś się coś pomieszało albo kolejna ofiara "buildów" czy gotowców z
chin (świeży przykład
https://www.wykop.pl/wpis/27006233/zakupilem-pierwszego-boxa-mecool-m8s-pro-nigdy-w-z/
nie ma czegoś takiego jak ranic... Więc obstawiam ramic).

25.09.2017 10:30 PM "ramicspa" <notifications@github.com> napisał(a):

jaki player?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/449#issuecomment-332002898>, or mute
the thread

**Comment by lampardzino** [comment]
tvn player

**Comment by tomasiek** [comment]
Tej wtyczki nie ma i nie było w repozytorium. Pisz do jej autora.

26.09.2017 3:28 PM "lampardzino" <notifications@github.com> napisał(a):

**Comment by kopernik1983** [comment]
@tomasiek rzuć no okiem na tę stronę http://cda-x.pl

**Comment by tomasiek** [comment]
https://github.com/ramicspa/kodi/issues/349#issuecomment-312168830
Było....
