### ISSUE TITLE
NIE popularne pytanie ...

### ISSUE THREAD

**Issue by meserak86** [ramicspa/kodi#527]
Jaki ukryty dla mnie sens ma  tworzenie wtyczek do portali które tak naprawde są scrapowane przez exodusa i forki??
czy nie lepiej tworzyc wtyczki do serwisow ktore nie obejmoja mega scrapery typu exodus+forki??
rozumiem, ze nadmiarowosc jest mile widziana, ale jest tu jakis glebszy sens??
czy nie lepiej by bylo sie wziasc za jakis projekt czegos czego nie ma/brakuje?
np audiobooki pl  / anime pl /

**Comment by tomasiek** [comment]
Exodus i forki padają. Wtyczki ramica nie. Exodus i forki wyszukują na
podstawie tytułów z trakt. Jeśli tam nie ma polskiego tytułu dodanego to
nie znajdą. Wtyczki ramica znajdą wszystko. Exodus i forki są mniej
dostosowane do polskich stron, działają ogólnie. Wtyczki ramica są skrojone
na miarę.

24.11.2017 11:14 PM "meserak86" <notifications@github.com> napisał(a):

Jaki ukryty dla mnie sens ma tworzenie wtyczek do portali które tak
naprawde są scrapowane przez exodusa i forki??
czy nie lepiej tworzyc wtyczki do serwisow ktore nie obejmoja mega scrapery
typu exodus+forki??
rozumiem, ze nadmiarowosc jest mile widziana, ale jest tu jakis glebszy
sens??

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/527>, or mute the thread

**Comment by meserak86** [comment]
calkowicie akceptuje takie wytlumaczenie:D

**Comment by tomasiek** [comment]
A co do nadmiarowości. Zwróć uwagę że tak naprawdę dzięki wtyczkom ramica
możesz sam zbudować działająca filmotekę, bez zbędnych rzeczy. Nie
interesuje cię sport czy telewizja, nie instalujesz. Za to jest kilka
niszowych jak ninateka, vider, film milicyjny, mp. Znajdź gdzieś odcinki mp
online... A tu są.

25.11.2017 6:11 AM "meserak86" <notifications@github.com> napisał(a):

calkowicie akceptuje takie wytlumaczenie:D

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ramicspa/kodi/issues/527#issuecomment-346919686>, or mute
the thread
